import { SelectOption } from './types';

// --- Image Constants ---

export const ART_STYLES: SelectOption[] = [
  { label: 'Select Style...', value: '' },
  { label: 'Photorealistic', value: 'photorealistic' },
  { label: 'Digital Art', value: 'digital art' },
  { label: 'Oil Painting', value: 'oil painting' },
  { label: 'Watercolor', value: 'watercolor' },
  { label: 'Sketch', value: 'charcoal sketch' },
  { label: '3D Render', value: '3D render (Octane Render)' },
  { label: 'Anime / Manga', value: 'anime style' },
  { label: 'Pixel Art', value: 'pixel art' },
  { label: 'Cyberpunk', value: 'cyberpunk aesthetic' },
  { label: 'Abstract', value: 'abstract' },
  { label: 'Minimalist', value: 'minimalist' },
  { label: 'Poster Style', value: 'poster art style' },
  { label: 'Infographic', value: 'infographic style' },
  { label: 'Surrealism', value: 'surrealism' },
  { label: 'Impressionism', value: 'impressionism' },
  { label: 'Pop Art', value: 'pop art' },
  { label: 'Ukiyo-e', value: 'ukiyo-e woodblock print' },
  { label: 'Steampunk', value: 'steampunk aesthetic' },
  { label: 'Art Deco', value: 'art deco' },
  { label: 'Art Nouveau', value: 'art nouveau' },
  { label: 'Graffiti / Street Art', value: 'graffiti street art' },
  { label: 'Low Poly', value: 'low poly 3d' },
  { label: 'Isometric', value: 'isometric 3d' },
  { label: 'Claymation', value: 'claymation style' },
  { label: 'Paper Cutout', value: 'paper cutout craft' },
  { label: 'Linocut', value: 'linocut print' },
  { label: 'Stained Glass', value: 'stained glass window' },
  { label: 'Ink Wash', value: 'ink wash painting' },
  { label: 'Pointillism', value: 'pointillism' },
  { label: 'Cubism', value: 'cubism' },
  { label: 'Fauvism', value: 'fauvism' },
  { label: 'Rococo', value: 'rococo style' },
  { label: 'Baroque', value: 'baroque style' },
  { label: 'Renaissance', value: 'renaissance painting' },
  { label: 'Concept Art', value: 'high concept art' },
  { label: 'Matte Painting', value: 'matte painting' },
  { label: 'Vector Art', value: 'vector art illustration' },
  { label: 'Flat Design', value: 'flat design' },
  { label: 'Kawaii', value: 'kawaii aesthetic' },
  { label: 'Gothic', value: 'gothic art' },
  { label: 'Noir', value: 'film noir style' },
  { label: 'Vaporwave', value: 'vaporwave aesthetic' },
  { label: 'Synthwave', value: 'synthwave aesthetic' },
  { label: 'Glitch Art', value: 'glitch art' },
  { label: 'Bauhaus', value: 'bauhaus style' },
];

export const COLOR_PALETTES: SelectOption[] = [
  { label: 'Default', value: '' },
  { label: 'Vibrant', value: 'vibrant colors' },
  { label: 'Pastel', value: 'pastel color palette' },
  { label: 'Monochrome', value: 'monochromatic' },
  { label: 'Warm Tones', value: 'warm color tones' },
  { label: 'Cool Tones', value: 'cool color tones' },
  { label: 'Neon', value: 'neon palette' },
  { label: 'Earth Tones', value: 'earthy tones' },
  { label: 'Black & White', value: 'black and white' },
  { label: 'Vintage', value: 'vintage fade' },
  { label: 'Sepia', value: 'sepia tone' },
  { label: 'Grayscale', value: 'grayscale' },
  { label: 'Technicolor', value: 'technicolor' },
  { label: 'Kodak Portra', value: 'Kodak Portra film look' },
  { label: 'Fujifilm', value: 'Fujifilm simulation' },
  { label: 'Polaroid', value: 'polaroid aesthetic' },
  { label: 'Duotone', value: 'duotone' },
  { label: 'Triadic', value: 'triadic colors' },
  { label: 'Complementary', value: 'complementary colors' },
  { label: 'Analogous', value: 'analogous colors' },
  { label: 'Split-Complementary', value: 'split-complementary colors' },
  { label: 'Tetradic', value: 'tetradic colors' },
  { label: 'Jewel Tones', value: 'jewel tones' },
  { label: 'Autumnal', value: 'autumn colors' },
  { label: 'Winter', value: 'winter colors' },
  { label: 'Spring', value: 'spring colors' },
  { label: 'Summer', value: 'summer colors' },
  { label: 'Rainbow', value: 'rainbow spectrum' },
  { label: 'Metallic', value: 'metallic colors' },
  { label: 'Gold & Black', value: 'gold and black' },
  { label: 'Teal & Orange', value: 'teal and orange' },
  { label: 'Desaturated', value: 'desaturated muted tones' },
  { label: 'High Contrast', value: 'high contrast' },
  { label: 'Low Contrast', value: 'low contrast' },
  { label: 'Cyberpunk Neon', value: 'cyberpunk neon colors' },
  { label: 'Cotton Candy', value: 'cotton candy pink and blue' },
  { label: 'Infrared', value: 'infrared photography' },
];

export const LIGHTING_OPTIONS: SelectOption[] = [
  { label: 'Default', value: '' },
  { label: 'Natural Light', value: 'natural lighting' },
  { label: 'Golden Hour', value: 'golden hour lighting' },
  { label: 'Studio Lighting', value: 'professional studio lighting' },
  { label: 'Dramatic Shadows', value: 'dramatic chiaroscuro lighting' },
  { label: 'Soft Diffused', value: 'soft diffused lighting' },
  { label: 'Cinematic', value: 'cinematic lighting' },
  { label: 'Neon Lighting', value: 'neon lighting' },
  { label: 'Bioluminescent', value: 'bioluminescent glow' },
  { label: 'Rembrandt Lighting', value: 'Rembrandt lighting' },
  { label: 'Butterfly Lighting', value: 'butterfly lighting' },
  { label: 'Split Lighting', value: 'split lighting' },
  { label: 'Loop Lighting', value: 'loop lighting' },
  { label: 'Rim Lighting (Backlight)', value: 'rim lighting' },
  { label: 'God Rays (Volumetric)', value: 'volumetric god rays' },
  { label: 'Lens Flare', value: 'lens flare' },
  { label: 'Firelight', value: 'warm firelight' },
  { label: 'Moonlight', value: 'cool moonlight' },
  { label: 'Starlight', value: 'starlight' },
  { label: 'Fluorescent', value: 'harsh fluorescent lighting' },
  { label: 'Incandescent', value: 'warm incandescent lighting' },
  { label: 'Candlelight', value: 'candlelight' },
  { label: 'Torchlight', value: 'flickering torchlight' },
  { label: 'Softbox', value: 'softbox lighting' },
  { label: 'Hard Light', value: 'hard directional light' },
  { label: 'Ring Light', value: 'ring light' },
  { label: 'Ambient Occlusion', value: 'ambient occlusion' },
  { label: 'Global Illumination', value: 'global illumination' },
  { label: 'Ray Traced', value: 'ray traced lighting' },
  { label: 'High Key', value: 'high key lighting' },
  { label: 'Low Key', value: 'low key lighting' },
  { label: 'Silhouette', value: 'silhouette' },
  { label: 'Noir Lighting', value: 'noir shadow patterns' },
  { label: 'Disco Lights', value: 'colorful disco lights' },
  { label: 'Underwater Caustics', value: 'underwater light caustics' },
];

export const CAMERA_ANGLES: SelectOption[] = [
  { label: 'Default', value: '' },
  { label: 'Eye Level', value: 'eye level' },
  { label: 'Bird\'s Eye View', value: 'bird\'s eye view' },
  { label: 'Worm\'s Eye View', value: 'worm\'s eye view' },
  { label: 'Low Angle', value: 'low angle' },
  { label: 'Dutch Angle', value: 'dutch angle' },
  { label: 'Over the Shoulder', value: 'over the shoulder' },
  { label: 'First Person POV', value: 'first person view' },
  { label: 'Fisheye Lens', value: 'fisheye lens' },
  { label: 'Telephoto Lens', value: 'telephoto lens' },
  { label: 'Macro Lens', value: 'macro lens' },
  { label: 'Wide-Angle Lens', value: 'wide-angle lens' },
  { label: 'Isometric View', value: 'isometric view' },
  { label: 'Drone Shot', value: 'drone shot' },
  { label: 'Satellite View', value: 'satellite view' },
  { label: 'GoPro View', value: 'GoPro wide angle' },
  { label: 'CCTV Perspective', value: 'security camera footage' },
  { label: 'Dashcam', value: 'dashcam footage' },
  { label: 'Selfie Angle', value: 'selfie angle' },
  { label: 'Overhead', value: 'directly overhead' },
  { label: 'Knee Level', value: 'knee level shot' },
  { label: 'Ground Level', value: 'ground level shot' },
  { label: 'Profile View', value: 'side profile view' },
  { label: 'Three-Quarter View', value: 'three-quarter view' },
  { label: 'Rear View', value: 'rear view' },
  { label: 'Action POV', value: 'action camera POV' },
  { label: 'Tilted', value: 'tilted frame' },
  { label: 'Rolling Shutter', value: 'rolling shutter effect' },
  { label: 'Panoramic', value: 'panoramic view' },
  { label: 'Microscopic', value: 'microscopic view' },
  { label: 'Telescopic', value: 'telescopic view' },
  { label: 'Through Window', value: 'shot through a window' },
  { label: 'Reflection', value: 'reflection in mirror/water' },
];

export const SHOT_TYPES: SelectOption[] = [
  { label: 'Default', value: '' },
  { label: 'Extreme Close-up', value: 'extreme close-up' },
  { label: 'Close-up', value: 'close-up' },
  { label: 'Medium Shot', value: 'medium shot' },
  { label: 'Wide Shot', value: 'wide shot' },
  { label: 'Full Body', value: 'full body shot' },
  { label: 'Macro', value: 'macro photography' },
  { label: 'Cowboy Shot', value: 'cowboy shot (knees up)' },
  { label: 'American Shot', value: 'American shot' },
  { label: 'Bust Shot', value: 'bust shot' },
  { label: 'Head and Shoulders', value: 'head and shoulders' },
  { label: 'Choker Shot', value: 'choker shot' },
  { label: 'Group Shot', value: 'group shot' },
  { label: 'Crowd Shot', value: 'crowd shot' },
  { label: 'Establishing Shot', value: 'establishing shot' },
  { label: 'Master Shot', value: 'master shot' },
  { label: 'Insert Shot', value: 'insert shot' },
  { label: 'Cutaway', value: 'cutaway shot' },
  { label: 'Point of View', value: 'POV shot' },
  { label: 'Over-the-hip', value: 'over-the-hip shot' },
  { label: 'Two-Shot', value: 'two-shot' },
  { label: 'Three-Shot', value: 'three-shot' },
  { label: 'Selfie', value: 'selfie' },
  { label: 'Silhouette Shot', value: 'silhouette shot' },
  { label: 'Focus Pull', value: 'rack focus' },
  { label: 'Tracking Shot', value: 'tracking shot' },
  { label: 'Dolly Zoom', value: 'dolly zoom effect' },
  { label: 'Time-Lapse', value: 'time-lapse' },
];

export const RESOLUTIONS: SelectOption[] = [
  { label: 'Default', value: '' },
  { label: '4K', value: '4K resolution' },
  { label: '8K', value: '8K resolution' },
  { label: 'High Detail', value: 'highly detailed' },
  { label: 'Cinematic Quality', value: 'cinematic quality' },
  { label: '16K', value: '16K resolution' },
  { label: '32K', value: '32K resolution' },
  { label: 'Full HD (1080p)', value: 'Full HD 1080p' },
  { label: 'HD (720p)', value: 'HD 720p' },
  { label: '2K (1440p)', value: '2K 1440p' },
  { label: 'Ultra HD', value: 'Ultra HD' },
  { label: 'IMAX', value: 'IMAX quality' },
  { label: 'Vector (SVG)', value: 'vector SVG quality' },
  { label: 'Super 35', value: 'Super 35 film' },
  { label: '70mm', value: '70mm film' },
  { label: '35mm', value: '35mm film' },
  { label: 'RAW Photo', value: 'RAW photo' },
  { label: 'Unreal Engine 5', value: 'Unreal Engine 5 render' },
  { label: 'Unity Engine', value: 'Unity Engine render' },
  { label: 'CryEngine', value: 'CryEngine render' },
  { label: 'V-Ray', value: 'V-Ray render' },
  { label: 'Corona Render', value: 'Corona Render' },
  { label: 'Redshift', value: 'Redshift render' },
  { label: 'Arnold', value: 'Arnold render' },
  { label: 'Blender Cycles', value: 'Blender Cycles render' },
  { label: 'Hyper-Realistic', value: 'hyper-realistic' },
  { label: 'Sharp Focus', value: 'sharp focus' },
  { label: 'Soft Focus', value: 'soft focus' },
  { label: 'Pixel Perfect', value: 'pixel perfect' },
];

export const ASPECT_RATIOS: SelectOption[] = [
  { label: '1:1 (Square)', value: '1:1 aspect ratio' },
  { label: '16:9 (Landscape)', value: '16:9 aspect ratio' },
  { label: '9:16 (Portrait)', value: '9:16 aspect ratio' },
  { label: '21:9 (Ultrawide)', value: '21:9 aspect ratio' },
  { label: '4:3', value: '4:3 aspect ratio' },
  { label: '3:2 (Classic 35mm)', value: '3:2 aspect ratio' },
  { label: '2:3 (Portrait 35mm)', value: '2:3 aspect ratio' },
  { label: '5:4 (Large Format)', value: '5:4 aspect ratio' },
  { label: '4:5 (IG Portrait)', value: '4:5 aspect ratio' },
  { label: '1.85:1 (Cinema)', value: '1.85:1 aspect ratio' },
  { label: '2.35:1 (Cinemascope)', value: '2.35:1 aspect ratio' },
  { label: '2.39:1 (Anamorphic)', value: '2.39:1 aspect ratio' },
  { label: '1:2', value: '1:2 aspect ratio' },
  { label: '2:1', value: '2:1 aspect ratio' },
  { label: '3:1 (Panoramic)', value: '3:1 aspect ratio' },
  { label: '1:3 (Vertical Pan)', value: '1:3 aspect ratio' },
  { label: '16:10', value: '16:10 aspect ratio' },
  { label: '5:3', value: '5:3 aspect ratio' },
  { label: '1.43:1 (IMAX)', value: '1.43:1 aspect ratio' },
  { label: '1:1.41 (A4)', value: 'A-series paper aspect ratio' },
];

export const ENVIRONMENTS: SelectOption[] = [
  { label: 'None specified', value: '' },
  { label: 'Indoor', value: 'interior setting' },
  { label: 'Outdoor', value: 'outdoor nature setting' },
  { label: 'Urban', value: 'busy urban city' },
  { label: 'Fantasy World', value: 'fantasy world environment' },
  { label: 'Sci-Fi', value: 'sci-fi futuristic setting' },
  { label: 'Space', value: 'deep space background' },
  { label: 'Studio', value: 'clean studio background' },
  { label: 'Post-Apocalyptic', value: 'post-apocalyptic wasteland' },
  { label: 'Cyberpunk City', value: 'neon cyberpunk cityscape' },
  { label: 'Steampunk Lab', value: 'steampunk laboratory' },
  { label: 'Victorian Mansion', value: 'victorian mansion interior' },
  { label: 'Ancient Ruins', value: 'ancient ruins' },
  { label: 'Underwater', value: 'underwater coral reef' },
  { label: 'Deep Jungle', value: 'dense jungle rain forest' },
  { label: 'Arctic', value: 'frozen arctic tundra' },
  { label: 'Desert', value: 'hot sandy desert' },
  { label: 'Volcano', value: 'volcanic crater' },
  { label: 'Space Station', value: 'futuristic space station' },
  { label: 'Moon', value: 'moon surface' },
  { label: 'Mars', value: 'mars colony' },
  { label: 'Medieval Castle', value: 'medieval castle' },
  { label: 'Wizard Tower', value: 'wizard\'s tower' },
  { label: 'Haunted House', value: 'spooky haunted house' },
  { label: 'Art Gallery', value: 'modern art gallery' },
  { label: 'Library', value: 'ancient library' },
  { label: 'Classroom', value: 'school classroom' },
  { label: 'Hospital', value: 'sterile hospital room' },
  { label: 'Factory', value: 'industrial factory' },
  { label: 'Warehouse', value: 'abandoned warehouse' },
  { label: 'Subway', value: 'subway station' },
  { label: 'Airport', value: 'busy airport terminal' },
  { label: 'Beach', value: 'tropical beach' },
  { label: 'Mountain Peak', value: 'snowy mountain peak' },
  { label: 'Swamp', value: 'misty swamp' },
  { label: 'Cave', value: 'dark cave' },
  { label: 'Garden', value: 'botanical garden' },
  { label: 'Kitchen', value: 'modern kitchen' },
  { label: 'Bedroom', value: 'cozy bedroom' },
];

export const MOODS: SelectOption[] = [
  { label: 'Default', value: '' },
  { label: 'Peaceful', value: 'peaceful and calm' },
  { label: 'Energetic', value: 'high energy and dynamic' },
  { label: 'Dark / Mysterious', value: 'dark and mysterious' },
  { label: 'Romantic', value: 'romantic atmosphere' },
  { label: 'Nostalgic', value: 'nostalgic feeling' },
  { label: 'Epic', value: 'epic and grandiose' },
  { label: 'Horror', value: 'horror and terrifying' },
  { label: 'Whimsical', value: 'whimsical and playful' },
  { label: 'Ethereal', value: 'ethereal and dreamlike' },
  { label: 'Melancholic', value: 'sad and melancholic' },
  { label: 'Joyful', value: 'happy and joyful' },
  { label: 'Angry', value: 'angry and aggressive' },
  { label: 'Tense', value: 'tense and suspenseful' },
  { label: 'Zen', value: 'zen and meditative' },
  { label: 'Chaotic', value: 'chaotic and disorderly' },
  { label: 'Love', value: 'loving and affectionate' },
  { label: 'Cybernetic', value: 'cold and cybernetic' },
  { label: 'Organic', value: 'organic and natural' },
  { label: 'Divine', value: 'divine and angelic' },
  { label: 'Demonic', value: 'demonic and hellish' },
  { label: 'Magical', value: 'magical and enchanting' },
  { label: 'Mundane', value: 'mundane and everyday' },
  { label: 'Surreal', value: 'surreal and bizarre' },
  { label: 'Dreamy', value: 'dreamy and soft' },
  { label: 'Nightmarish', value: 'nightmarish and unsettling' },
  { label: 'Grotesque', value: 'grotesque and weird' },
  { label: 'Cute', value: 'cute and adorable' },
  { label: 'Minimal', value: 'stark and minimal' },
  { label: 'Opulent', value: 'opulent and luxurious' },
  { label: 'Gritty', value: 'gritty and dirty' },
  { label: 'Sterile', value: 'sterile and clean' },
  { label: 'Cozy', value: 'cozy and comfortable' },
  { label: 'Lonely', value: 'lonely and isolated' },
  { label: 'Hopeful', value: 'hopeful and uplifting' },
];

// --- Text Constants ---

export const PURPOSES: SelectOption[] = [
  { label: 'Select Purpose...', value: '' },
  { label: 'Creative Writing', value: 'creative writing' },
  { label: 'Code Generation', value: 'software coding' },
  { label: 'Analysis', value: 'analytical breakdown' },
  { label: 'Summarization', value: 'summarization' },
  { label: 'Translation', value: 'translation' },
  { label: 'Brainstorming', value: 'ideation and brainstorming' },
  { label: 'Roleplay', value: 'character roleplay' },
  { label: 'Email Drafting', value: 'drafting an email' },
  { label: 'Blog Post', value: 'writing a blog post' },
  { label: 'Social Media Caption', value: 'social media caption' },
  { label: 'SEO Article', value: 'SEO-optimized article' },
  { label: 'Product Description', value: 'e-commerce product description' },
  { label: 'Technical Documentation', value: 'technical documentation' },
  { label: 'User Manual', value: 'user manual instructions' },
  { label: 'Cover Letter', value: 'job application cover letter' },
  { label: 'Resume/CV', value: 'resume or CV' },
  { label: 'Grant Proposal', value: 'grant proposal' },
  { label: 'Business Plan', value: 'business plan' },
  { label: 'Marketing Copy', value: 'marketing ad copy' },
  { label: 'Slogan Generation', value: 'catchy slogan generation' },
  { label: 'Poem', value: 'writing a poem' },
  { label: 'Song Lyrics', value: 'song lyrics' },
  { label: 'Script Writing', value: 'video or movie script' },
  { label: 'Dialogue', value: 'conversation dialogue' },
  { label: 'Joke Writing', value: 'writing jokes' },
  { label: 'Math Problem', value: 'solving a math problem' },
  { label: 'SQL Query', value: 'generating SQL queries' },
  { label: 'Regex', value: 'generating regular expressions' },
  { label: 'Unit Tests', value: 'writing software unit tests' },
  { label: 'API Docs', value: 'API documentation' },
  { label: 'Git Commit', value: 'git commit message' },
  { label: 'Recipe', value: 'cooking recipe' },
  { label: 'Workout Plan', value: 'fitness workout plan' },
  { label: 'Travel Itinerary', value: 'travel itinerary' },
  { label: 'Study Guide', value: 'academic study guide' },
];

export const WRITING_STYLES: SelectOption[] = [
  { label: 'Default', value: '' },
  { label: 'Professional', value: 'professional and corporate' },
  { label: 'Academic', value: 'academic and scholarly' },
  { label: 'Creative', value: 'creative and descriptive' },
  { label: 'Conversational', value: 'casual and conversational' },
  { label: 'Technical', value: 'technical and precise' },
  { label: 'Journalistic', value: 'journalistic' },
  { label: 'Poetic', value: 'poetic and lyrical' },
  { label: 'Satirical', value: 'satirical' },
  { label: 'Sarcastic', value: 'sarcastic' },
  { label: 'Narrative', value: 'narrative storytelling' },
  { label: 'Descriptive', value: 'highly descriptive' },
  { label: 'Expository', value: 'expository' },
  { label: 'Persuasive', value: 'persuasive' },
  { label: 'Argumentative', value: 'argumentative' },
  { label: 'Analytical', value: 'analytical' },
  { label: 'Critical', value: 'critical review' },
  { label: 'Reflective', value: 'reflective and introspective' },
  { label: 'Personal', value: 'first-person personal' },
  { label: 'Objective', value: 'objective and unbiased' },
  { label: 'Subjective', value: 'subjective and opinionated' },
  { label: 'Abstract', value: 'abstract and philosophical' },
  { label: 'Concise', value: 'concise and to the point' },
  { label: 'Verbose', value: 'verbose and elaborate' },
  { label: 'Flowery', value: 'flowery prose' },
  { label: 'Minimalist', value: 'minimalist' },
  { label: 'Hemingway-esque', value: 'Hemingway style (short, punchy)' },
  { label: 'Shakespearean', value: 'Shakespearean Early Modern English' },
  { label: 'Victorian', value: 'Victorian English' },
  { label: 'Gonzo', value: 'Gonzo journalism' },
  { label: 'Tabloid', value: 'sensationalist tabloid style' },
  { label: 'Legal', value: 'legalese' },
  { label: 'Medical', value: 'medical terminology' },
  { label: 'Scientific', value: 'scientific report style' },
  { label: 'Corporate Speak', value: 'corporate jargon' },
  { label: 'ELI5', value: 'Explain Like I\'m 5' },
];

export const TONES: SelectOption[] = [
  { label: 'Default', value: '' },
  { label: 'Neutral', value: 'neutral' },
  { label: 'Friendly', value: 'friendly and warm' },
  { label: 'Authoritative', value: 'authoritative and confident' },
  { label: 'Humorous', value: 'humorous and witty' },
  { label: 'Empathetic', value: 'empathetic and understanding' },
  { label: 'Persuasive', value: 'persuasive' },
  { label: 'Sarcastic', value: 'sarcastic' },
  { label: 'Cynical', value: 'cynical' },
  { label: 'Optimistic', value: 'optimistic' },
  { label: 'Pessimistic', value: 'pessimistic' },
  { label: 'Skeptical', value: 'skeptical' },
  { label: 'Naive', value: 'naive' },
  { label: 'Inspirational', value: 'inspirational' },
  { label: 'Motivational', value: 'motivational' },
  { label: 'Urgent', value: 'urgent' },
  { label: 'Calm', value: 'calm' },
  { label: 'Relaxed', value: 'relaxed' },
  { label: 'Stressed', value: 'stressed' },
  { label: 'Formal', value: 'formal' },
  { label: 'Informal', value: 'informal' },
  { label: 'Slang-heavy', value: 'slang-heavy' },
  { label: 'Childish', value: 'childish' },
  { label: 'Mature', value: 'mature' },
  { label: 'Romantic', value: 'romantic' },
  { label: 'Platonic', value: 'platonic' },
  { label: 'Aggressive', value: 'aggressive' },
  { label: 'Passive-Aggressive', value: 'passive-aggressive' },
  { label: 'Defensive', value: 'defensive' },
  { label: 'Apologetic', value: 'apologetic' },
  { label: 'Grateful', value: 'grateful' },
  { label: 'Humble', value: 'humble' },
  { label: 'Arrogant', value: 'arrogant' },
  { label: 'Melodramatic', value: 'melodramatic' },
  { label: 'Deadpan', value: 'deadpan' },
  { label: 'Whimsical', value: 'whimsical' },
];

export const LENGTHS: SelectOption[] = [
  { label: 'Any', value: '' },
  { label: 'Brief (1-2 sentences)', value: 'very brief, 1-2 sentences' },
  { label: 'Short (1 paragraph)', value: 'short, one paragraph' },
  { label: 'Medium (2-3 paragraphs)', value: 'medium length, 2-3 paragraphs' },
  { label: 'Long (500+ words)', value: 'extensive, over 500 words' },
  { label: 'Detailed Report', value: 'comprehensive detailed report' },
  { label: 'Bullet Points', value: 'formatted as bullet points' },
  { label: 'Single Word', value: 'a single word' },
  { label: 'Tweet (<280 chars)', value: 'under 280 characters' },
  { label: 'Instagram Caption', value: 'short social media caption' },
  { label: 'LinkedIn Post', value: 'professional LinkedIn post length' },
  { label: 'Short Blog (300w)', value: 'short blog post (~300 words)' },
  { label: 'Standard Blog (1000w)', value: 'standard blog post (~1000 words)' },
  { label: 'Long Article (2000w+)', value: 'long-form article (2000+ words)' },
  { label: 'Short Story', value: 'short story' },
  { label: 'Novella', value: 'novella length' },
  { label: 'Novel Chapter', value: 'one chapter of a novel' },
  { label: 'Screenplay Scene', value: 'one scene of a screenplay' },
  { label: 'Haiku', value: 'haiku (5-7-5 syllables)' },
  { label: 'Sonnet', value: 'sonnet (14 lines)' },
  { label: 'Limerick', value: 'limerick' },
  { label: 'Elevator Pitch', value: '30-second elevator pitch' },
  { label: 'Abstract (150w)', value: 'academic abstract (~150 words)' },
  { label: 'Executive Summary', value: 'executive summary' },
  { label: 'One Page', value: 'exactly one page' },
  { label: 'Ten Pages', value: 'ten pages' },
];